[project]
name = "uptime-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "requests>=2.32.5",
    "psycopg[binary]>=2.9.10",
    "typer>=0.12.0",
]
